// problem 2.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"

#define ISEVEN(N) ((N%2==0)?1:0)
#define FIBONACCI_LIMIT		4000000
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

int fibonacci(int i);
int _tmain(int argc, _TCHAR* argv[])
{
	int i;
	long fibNum = 0;
	long fibEvenSum = 0;

	for (i = 1; i < 10000; i++) {
		fibNum = fibonacci(i);
		if (fibNum > FIBONACCI_LIMIT)
			break; 
		if (ISEVEN(fibNum)){
			fibEvenSum += fibNum;
		}
	}

	printf("find the sum of the even-valued terms in the fibonacci sequence is (%d) ", fibEvenSum);

	return 0;
}

int fibonacci(int i) {
	if (i == 0) {
		return 0;
	}  else if (i == 1) {
		return 1;
	}

	return fibonacci(i - 1) + fibonacci(i - 2);
}
